project_id   = "kube-projects-427711"
region       = "us-central1"
cluster_name = "kube-cluster"
service_account = "gke-terraform-actions@kube-projects-427711.iam.gserviceaccount.com"
zone            = "us-central1-c"
