name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform/

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: terraform/

    - name: Set up kubeconfig
      run: |
        gcloud container clusters get-credentials kube-cluster --zone us-central1-c --project ${{ secrets.GCP_PROJECT }}

    - name: Deploy application
      run: |
        kubectl apply -f k8s/pre-ingress.yaml
        kubectl apply -f k8s/hpa.yaml

    - name: Verify deployment
      run: kubectl get pods
