name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform/

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: terraform/

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > key.json
        gcloud auth activate-service-account --key-file=key.json
        gcloud container clusters get-credentials ${CLUSTER_NAME} --zone ${ZONE}

    - name: Deploy application
      run: |
        kubectl apply -f k8s/pre-ingress.yaml
        kubectl apply -f k8s/hpa.yaml

    - name: Verify deployment
      run: kubectl get pods
